export BUILT_PRODUCTS_DIR="/Users/basvankuijck/Library/Developer/Xcode/DerivedData/ESDateHelper-elkbwjcuykajrqfzuwfrlcmwdvnr/Build/Products/Debug-iphonesimulator"
export CURRENT_ARCH="i386"
export OBJECT_FILE_DIR_normal="/Users/basvankuijck/Library/Developer/Xcode/DerivedData/ESDateHelper-elkbwjcuykajrqfzuwfrlcmwdvnr/Build/Intermediates/ESDateHelper.build/Debug-iphonesimulator/ESDateHelper.build/Objects-normal"
export OBJROOT="/Users/basvankuijck/Library/Developer/Xcode/DerivedData/ESDateHelper-elkbwjcuykajrqfzuwfrlcmwdvnr/Build/Intermediates"
export PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR="YES"
export SRCROOT="/Users/basvankuijck/Desktop/pods/ESDateHelper"
